export type DriverData = {
    organizationId: string;
    name: string;
    phone?: string | null;
    email?: string | null;
    address?: string | null;
    nationality?: string | null;
    birthDate?: Date | null;
    languages?: string[];
    emergencyContact?: string | null;
    employmentStatus?: "EMPLOYEE" | "FREELANCE" | "SUBCONTRACTOR" | null;
    vtcCardNumber?: string | null;
    vtcCardIssuedAt?: Date | null;
    vtcCardExpiresAt?: Date | null;
    driverLicenseNumber?: string | null;
    licenseCategory?: string | null;
    licenseIssuedAt?: Date | null;
    licenseExpiresAt?: Date | null;
    drivingExperienceYears?: number | null;
    hasVipExperience?: boolean;
    hasEventExperience?: boolean;
    languageLevel?: string | null;
    dressCodeReady?: boolean;
    passportProvided?: boolean;
    driverLicenseProvided?: boolean;
    vtcCardProvided?: boolean;
    criminalRecordProvided?: boolean;
    medicalCertificateProvided?: boolean;
    insuranceProofProvided?: boolean;
    profilePhotoProvided?: boolean;
    signedContractProvided?: boolean;
    baseCity?: string | null;
    workingRadiusKm?: number | null;
    acceptsLongDistance?: boolean;
    acceptsNightTrips?: boolean;
    acceptsAirportTransfers?: boolean;
    acceptsVipClients?: boolean;
    availabilityDays?: string[];
    availabilityHours?: string | null;
    hasOwnVehicle?: boolean;
    vehicle: string;
    vehiclePlate: string;
    vehicleColor: string;
    status: boolean;
    rides: number;
    todayShift: string;
};