import type { DriverOrganizationFormValues } from "../../data/types";

export const defaultFormValues: DriverOrganizationFormValues = {
  id: "",
  organizationName: "",
  email: "",
  phone: "",
  contactPerson: "",
  status: true,

  legalForm: "",
  sirenOrSiret: "",
  vatNumber: "",
  registrationDate: "",
  registrationCountry: "France",
  registeredAddress: "",
  sameAsRegisteredAddress: false,
  websiteUrl: "",
  directorFullName: "",
  directorPosition: "",

  kbisUploaded: false,
  rcProInsuranceUploaded: false,
  transportInsuranceUploaded: false,
  operatingLicenseProvided: false,
  bankDetailsProvided: false,
  directorIdCopyProvided: false,
  signedPartnershipAgreement: false,
  additionalCertifications: "",
  documentNotes: "",

  serviceAreas: "",
  serviceTypes: [],
  workingHours: "",
  support24_7: false,
  languagesSpoken: [],
  maxConcurrentBookings: "",
  minAdvanceBookingHours: "",
  acceptsUrgentBookings: false,
  cancellationPolicy: "",
  specialConditionsNotes: "",

  cooperationType: "",
  bankAccountIban: "",
  paymentTerms: "",
  commissionPercent: "",
  currency: "EUR",
  minimumFare: "",
  hourlyRate: "",
  transferBaseRate: "",
  nightSurchargePercent: "",
  holidaySurchargePercent: "",
  waitingTimeFee: "",
};
