-- AlterTable
ALTER TABLE "Bookings" ADD COLUMN     "candidateVehicleIds" TEXT[] DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "vehicleId" SET DEFAULT '',
ALTER COLUMN "from" DROP DEFAULT,
ALTER COLUMN "to" DROP DEFAULT,
ALTER COLUMN "clientEmail" DROP DEFAULT,
ALTER COLUMN "clientPhone" DROP DEFAULT,
ALTER COLUMN "tripType" DROP DEFAULT;
