import { toNumber } from "../../../../../../utils/transform";
import type { Driver, DriverFormValues } from "../types";
import {
  defaultFormValues,
} from "./driverManagementForm.types";
import { commonContent } from "../../../../../../content/common";
import { driverAgentsContent } from "../../../../../../content/driverAgents";

export function driverToFormValues(driver: Driver | null): DriverFormValues {
  if (!driver) return defaultFormValues;

  return {
    name: driver.name ?? "",
    phone: driver.phone ?? "",
    email: driver.email ?? "",
    address: driver.address ?? "",
    nationality: driver.nationality ?? "",
    birthDate: driver.birthDate ?? undefined,
    languages: driver.languages ?? [],
    emergencyContact: driver.emergencyContact ?? "",
    employmentStatus: driver.employmentStatus ?? null,
    vtcCardNumber: driver.vtcCardNumber ?? "",
    vtcCardIssuedAt: driver.vtcCardIssuedAt ?? undefined,
    vtcCardExpiresAt: driver.vtcCardExpiresAt ?? undefined,
    driverLicenseNumber: driver.driverLicenseNumber ?? "",
    licenseCategory: driver.licenseCategory ?? "",
    licenseIssuedAt: driver.licenseIssuedAt ?? undefined,
    licenseExpiresAt: driver.licenseExpiresAt ?? undefined,
    drivingExperienceYears: driver.drivingExperienceYears ?? undefined,
    hasVipExperience: driver.hasVipExperience ?? false,
    hasEventExperience: driver.hasEventExperience ?? false,
    languageLevel: driver.languageLevel ?? "",
    dressCodeReady: driver.dressCodeReady ?? false,
    passportProvided: driver.passportProvided ?? false,
    driverLicenseProvided: driver.driverLicenseProvided ?? false,
    vtcCardProvided: driver.vtcCardProvided ?? false,
    criminalRecordProvided: driver.criminalRecordProvided ?? false,
    medicalCertificateProvided: driver.medicalCertificateProvided ?? false,
    insuranceProofProvided: driver.insuranceProofProvided ?? false,
    profilePhotoProvided: driver.profilePhotoProvided ?? false,
    signedContractProvided: driver.signedContractProvided ?? false,
    baseCity: driver.baseCity ?? "",
    workingRadiusKm:
      driver.workingRadiusKm ?? undefined,
    acceptsLongDistance: driver.acceptsLongDistance ?? false,
    acceptsNightTrips: driver.acceptsNightTrips ?? false,
    acceptsAirportTransfers: driver.acceptsAirportTransfers ?? false,
    acceptsVipClients: driver.acceptsVipClients ?? false,
    availabilityDays: driver.availabilityDays ?? [],
    availabilityHours: driver.availabilityHours ?? undefined,
    hasOwnVehicle: driver.hasOwnVehicle ?? false,
    vehicle: driver.vehicle ?? undefined,
    vehiclePlate: driver.vehiclePlate ?? undefined,
    vehicleColor: driver.vehicleColor ?? undefined,
    status: driver.status ?? true,
    rides: driver.rides ?? undefined,
    todayShift: driver.todayShift ?? undefined,
  };
}

export function FormValuesToDriver(
  values: DriverFormValues,
  organizationId: string,
): Driver {

  return {
    organizationId,
    organizationName: "",
    name: values.name.trim() || driverAgentsContent.vehicle.unnamedDriver,
    phone: values.phone?.trim() || undefined,
    email: values.email?.trim() || undefined,
    address: values.address?.trim() || undefined,
    nationality: values.nationality?.trim() || undefined,
    birthDate: values.birthDate || undefined,
    languages: values.languages,
    emergencyContact: values.emergencyContact?.trim() || undefined,
    employmentStatus: values.employmentStatus || undefined,
    vtcCardNumber: values.vtcCardNumber?.trim() || undefined,
    vtcCardIssuedAt: values.vtcCardIssuedAt || undefined,
    vtcCardExpiresAt: values.vtcCardExpiresAt || undefined,
    driverLicenseNumber: values.driverLicenseNumber?.trim() || undefined,
    licenseCategory: values.licenseCategory?.trim() || undefined,
    licenseIssuedAt: values.licenseIssuedAt || undefined,
    licenseExpiresAt: values.licenseExpiresAt || undefined,
    drivingExperienceYears: toNumber(values.drivingExperienceYears),
    hasVipExperience: values.hasVipExperience,
    hasEventExperience: values.hasEventExperience,
    languageLevel: values.languageLevel?.trim() || undefined,
    dressCodeReady: values.dressCodeReady,
    passportProvided: values.passportProvided,
    driverLicenseProvided: values.driverLicenseProvided,
    vtcCardProvided: values.vtcCardProvided,
    criminalRecordProvided: values.criminalRecordProvided,
    medicalCertificateProvided: values.medicalCertificateProvided,
    insuranceProofProvided: values.insuranceProofProvided,
    profilePhotoProvided: values.profilePhotoProvided,
    signedContractProvided: values.signedContractProvided,
    baseCity: values.baseCity?.trim() || undefined,
    workingRadiusKm: toNumber(values.workingRadiusKm),
    acceptsLongDistance: values.acceptsLongDistance,
    acceptsNightTrips: values.acceptsNightTrips,
    acceptsAirportTransfers: values.acceptsAirportTransfers,
    acceptsVipClients: values.acceptsVipClients,
    availabilityDays: values.availabilityDays,
    availabilityHours: values.availabilityHours?.trim() || undefined,
    hasOwnVehicle: values.hasOwnVehicle,
    vehicle: values.vehicle?.trim() || driverAgentsContent.vehicle.unknown,
    vehiclePlate: values.vehiclePlate?.trim() || commonContent.notApplicable,
    vehicleColor: values.vehicleColor?.trim() || commonContent.notApplicable,
    status: values.status ?? true,
    rides: toNumber(values.rides),
    todayShift: values.todayShift?.trim() || undefined,
  };
}
