import type { DriverOrganization } from "../../../data/types";

export const defaultFormValues: DriverOrganization = {
  id: "",

  legalForm: "",
  sirenOrSiret: "",
  vatNumber: "",
  registrationDate: "",
  registrationCountry: "France",
  registeredAddress: "",
  mailingAddress: "",
  sameAsRegisteredAddress: false,
  websiteUrl: "",
  generalEmail: "",
  companyPhoneNumber: "",
  directorFullName: "",
  directorPosition: "",
  primaryContactName: "",
  primaryContactEmail: "",
  primaryContactPhone: "",

  kbisUploaded: false,
  rcProInsuranceUploaded: false,
  transportInsuranceUploaded: false,
  operatingLicenseProvided: false,
  bankDetailsProvided: false,
  directorIdCopyProvided: false,
  signedPartnershipAgreement: false,
  additionalCertifications: "",
  documentNotes: "",

  serviceAreas: "",
  serviceTypes: [],
  workingHours: "",
  support24_7: false,
  languagesSpoken: [],
  maxConcurrentBookings: "",
  minAdvanceBookingHours: "",
  acceptsUrgentBookings: false,
  cancellationPolicy: "",
  specialConditionsNotes: "",

  cooperationType: null,
  bankAccountIban: "",
  paymentTerms: "",
  commissionPercent: "",
  currency: "EUR",
  minimumFare: "",
  hourlyRate: "",
  transferBaseRate: "",
  nightSurchargePercent: "",
  holidaySurchargePercent: "",
  waitingTimeFee: "",
};
