import type { SecurityOrganizationFormValues } from "../../data/types";

export const defaultFormValues: SecurityOrganizationFormValues = {
  id: "",
  organizationName: "",
  email: "",
  phone: "",
  contactPerson: "",
  status: true,

  legalForm: "",
  sirenOrSiret: "",
  licenseNumber: "",
  cnapsNumber: "",
  registrationDate: "",
  registeredAddress: "",
  officeAddress: "",
  websiteUrl: "",
  directorFullName: "",

  kbisUploaded: false,
  licenseUploaded: false,
  rcProInsuranceUploaded: false,
  cnapsAuthorizationUploaded: false,
  bankDetailsProvided: false,
  directorIdCopyProvided: false,
  signedPartnershipAgreement: false,
  additionalCertifications: "",

  serviceAreas: "",
  serviceTypes: [],
  support24_7: false,
  minBookingHours: "",
  mobilizationTimeMinutes: "",
  agentsCount: "",
  languagesSpoken: [],
  hasTeamLeader: false,
  armedPersonnelAllowed: false,
  unarmedPersonnelAllowed: true,
  internationalMissions: false,
  specialRequirements: "",

  hourlyRate: "",
  dailyRate: "",
  nightRate: "",
  eventRate: "",
  executiveProtectionRate: "",
  minimumBookingAmount: "",
  commissionPercent: "",
  paymentTerms: "",
  bankAccountIban: "",
  currency: "EUR",
};
