export type SecurityAgent = {
    id: string;
    organizationId: string;
    firstName: string;
    lastName: string;
    birthDate: string | null;
    nationality: string | null;
    profilePhotoUrl: string | null;
    phone: string | null;
    email: string | null;
    address: string | null;
    languages: string[];
    emergencyContact: string | null;
    employmentStatus: string | null;
    professionalCardNumber: string | null;
    cnapsNumber: string | null;
    cardIssuedAt: string | null;
    cardExpiresAt: string | null;
    specializations: string[];
    experienceYears: number | null;
    hasVipExperience: boolean;
    hasEventExperience: boolean;
    hasDriverLicenseB: boolean;
    additionalLicenses: string | null;
    physicalLevel: string | null;
    hasFirstAidTraining: boolean;
    weaponExperience: boolean;
    readyForTravel: boolean;
    readyForNightShifts: boolean;
    passportProvided: boolean;
    professionalCardProvided: boolean;
    cnapsProvided: boolean;
    cvProvided: boolean;
    certificatesProvided: boolean;
    firstAidCertificateProvided: boolean;
    driverLicenseProvided: boolean;
    backgroundCheckProvided: boolean;
    profilePhotoProvided: boolean;
    signedContractProvided: boolean;
    baseCity: string | null;
    workingRadiusKm: number | null;
    availability: string | null;
    hourlyRate: string | null;
    dailyRate: string | null;
    nightRate: string | null;
    canWorkInTeam: boolean;
    canTravelWithClient: boolean;
    canDoDriverSecurity: boolean;
    status: boolean;
    notes: string | null;
    createdAt: string;
    updatedAt: string;
};
